### ISSUE TITLE
how to link with the LAPACK library

### ISSUE THREAD

**Issue by FannieGerosa** [Turbulence-Master/ProjectFortran#11]
Hello, 
I have some difficulties to link my module with this library, should I change even the Makefile?

**Comment by trblnc** [comment]
Yes, you need to that. 

First you need to be sure lapack is installed in your system. And you need to know where is the library. 

So you need a link the libraries in to the your compilation line

 `gfortran -L/usr/local/lib -llapackf -lblas`

Inside a the makefile it can be done more clean by adding `FLIBS` variable.

So you need an update something similar to that:
```
LIB          = -L/usr/local/lib 
FLIBS     =  $(LIB) -llapack -lblas

tools.o: tools.f90
	gfortran -c tools.f90 $(FLIBS) 
```

On the other hand we decide to this with an easier way at the class; CMakeList file is still missing #6, I dont know why.

**Comment by guilindner** [comment]
I updated the Makefile, but it is only compiling the test case (generalTest.f90) using Lapack and some class_field examples

**Comment by trblnc** [comment]
Thanks @guilindner. Hopefully this will be solved completely once we have CMakeLists.txt ready.

**Comment by trblnc** [comment]
Hi @FannieGerosa, I am closing this issue, assuming it was solved. Let me know if it is not the case.
