### ISSUE TITLE
.gitignore does not take care of doxygen generated files

### ISSUE THREAD

**Issue by trblnc** [Turbulence-Master/ProjectFortran#2]
doxygen can create quite a lot of stuff. 

I think we should keep only doxyfile inside the repo; but not all the other files generated by doxyfile. 

So .gitignore suppose to be updated accordingly. @guilindner @FannieGerosa @ElAdawyhassan @Turbulent-wero @anandutsav

**Comment by guilindner** [comment]
solved on commit 826adc5
