### ISSUE TITLE
Missing CMakeLists.txt file

### ISSUE THREAD

**Issue by trblnc** [Turbulence-Master/ProjectFortran#6]
I believe we can have initial version of this file already. 

Please look at the [example](https://github.com/trblnc/CMakeExample/blob/master/CMakeLists.txt) I showed in the class. Up to line 20-25 is a good start already.

**Comment by trblnc** [comment]
Any improvements on this?

**Comment by guilindner** [comment]
I did an initial commit  444af1d, for now is just compiling the main.f90 executable. I will test the other programs and try to add to it.

**Comment by trblnc** [comment]
I think we are good on this for the moment, let's try to close it once more.
